### ISSUE TITLE
Research paper

### ISSUE THREAD

**Issue by rishikksh20** [xcmyz/CLONE#1]
Hi @xcmyz ,
Your research looks very promising as a single-stage TTS, but I am not able to find a research paper anywhere. 
Are you able to share your research paper?

Thanks

**Comment by xcmyz** [comment]
> Hi @xcmyz , Your research looks very promising as a single-stage TTS, but I am not able to find a research paper anywhere. Are you able to share your research paper?
> 
> Thanks

It will be posted on arxiv tomorrow.😊

**Comment by rishikksh20** [comment]
thanks
